services:
  webapi:
    build:
      context: .
      target: final

    # expose port 80 to postman/newman for running API collection
    expose: 
      - 80
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost/health || exit 1"
      interval: 1s
      timeout: 5s
      retries: 5

  automator:
    build:
      context: ./Postman
    depends_on:
      webapi:
        condition: service_healthy

    # set the Postman collection environment variable "baseUrl" to be the service name in this file, "webapi"
    # and run the following command from the default entrypoint, newman
    command: ["run", "--env-var", "baseUrl=webapi", "BillDemoApi.postman_collection.json"]
    tty: true 

